### ISSUE TITLE
Scripts don't load on HTTPS on https://datanews.github.io/tik-tok/

### ISSUE THREAD

**Issue by benlk** [datanews/tik-tok#23]
Scripts don't load on https://datanews.github.io/tik-tok/, but do load on http://datanews.github.io/tik-tok/

It's because the site is trying to load HTTP content on an HTTPS page. A find-and-replace on branch `gh-pages` from `http://` to `https://` should fix the problem, but there might be other issues.

**Comment by zzolo** [comment]
Thanks Ben.  We should actually use `//` which will figure it out for us.  Also, I will also have to check to see if the hosted resources all support `https`.

**Comment by zzolo** [comment]
I was wrong about the protocol agnostic stuff:
http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by benlk** [comment]
Looks good now!
